//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TimerProject.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLDATEDATAS
    {
        public int id { get; set; }
        public Nullable<int> summinute { get; set; }
        public Nullable<System.DateTime> date { get; set; }
        public string datetime { get; set; }
        public string datestr { get; set; }
        public Nullable<System.DateTime> datetimedt { get; set; }
    }
}
