//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TimerProject.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLSYSTEMINFO
    {
        public int id { get; set; }
        public Nullable<System.DateTime> targetdate { get; set; }
        public string targetdatestr { get; set; }
    }
}
